#!/usr/bin/env Rscript
args = commandArgs(trailingOnly=TRUE)
sim = as.integer(args[1])
om = as.integer(args[2])
em = as.integer(args[3])
.libPaths("~/Rlib/")
library(wham)
source(file.path(here::here(), "Project_0","code", "sim_management.R"))
verify_version()
#cat(paste0("number of cores available: ", parallel::detectCores(), "/n"))
#stop()
run_hpcc_jobs(this_sim = sim, this_om = om, this_em = em)
#job.sheet = checkout_jobs(sims = 6, member = "TJM")
#job.sheet = update_job_sheet_commits(sims = 6, job.sheet= job.sheet)